backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title for tab and URL", name: "title", widget: "string" }
      - { label: "Publish date for sorting", name: "date", widget: "datetime" }
      - { label: "Search engine description", name: "description", widget: "text" }
      - { label: "Featured image", name: "featuredImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Categories", name: "categories", widget: "list" }
